# version: '3.8'
# networks:
#   monitoring:
#     driver: bridge
# volumes:
#   prometheus-data:
#     driver: local
#   grafana-data:
#     driver: local
# services:
#   prometheus:
#     image: prom/prometheus:v2.37.9
#     container_name: prometheus
#     ports:
#       - 9090:9090
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yaml'
#     volumes:
#       - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
#       - ./prometheus_data:/prometheus/data
#     restart: unless-stopped
#   grafana:
#     image: grafana/grafana-oss:latest
#     container_name: grafana
#     ports:
#       - '3000:3000'
#     volumes:
#       - grafana-data:/var/lib/grafana
#     restart: unless-stopped
#     #password: root123
#   node_exporter:
#     image: quay.io/prometheus/node-exporter:v1.5.0
#     container_name: node_exporter
#     command: '--path.rootfs=/host'
#     pid: host
#     restart: unless-stopped
#     volumes:
#       - /:/host:ro,rslave
#   cadvisor:
#     image: gcr.io/cadvisor/cadvisor:v0.47.0
#     container_name: cadvisor
#     command:
#       - '-port=8098'
#     volumes:
#       - /:/rootfs:ro
#       - /var/run:/var/run:ro
#       - /sys:/sys:ro
#       - /var/lib/docker/:/var/lib/docker:ro
#       - /dev/disk/:/dev/disk:ro
#     devices:
#       - /dev/kmsg
#     privileged: true
#     restart: unless-stopped




# version: '3.3'

# networks:
#   monitoring:
#     driver: bridge

# volumes:
#   prometheus_data:
#     driver: local
#   grafana-data:
#     driver: local

# services:
#   node-exporter:
#     image: prom/node-exporter:latest
#     container_name: node-exporter
#     restart: unless-stopped
#     volumes:
#       - /proc:/host/proc:ro
#       - /sys:/host/sys:ro
#       - /:/rootfs:ro
#     command:
#       - '--path.procfs=/host/proc'
#       - '--path.rootfs=/rootfs'
#       - '--path.sysfs=/host/sys'
#       - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#     ports:
#       - 9293:9293
#     networks:
#       - monitoring
  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - prometheus
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     restart: unless-stopped
#     volumes:
#       - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     ports:
#       - 9090:9090
#     networks:
#       - monitoring

version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  

