# global:
#   scrape_interval: 15s
# scrape_configs:
#   - job_name: 'prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['0.0.0.0:9090']
#     metrics_path: '/tam-metrics'
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node_exporter:9100']

#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:8098']

# global:
#   scrape_interval:     15s

# scrape_configs:
#   - job_name: "prometheus"
#     scrape_interval: 5s
#     static_configs:
#     - targets: ["127.0.0.1:9090"]

#   - job_name: "node-exporter"
#     static_configs:
#     metrics_path: '/metrics'
#     - targets: ["172.17.0.1:9293"]

#   - job_name: docker
#     scrape_interval: 5s
#     static_configs:
#     - targets:
#       - 172.17.0.1:9323

global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']


    